apiVersion: apps/v1
kind: Deployment

metadata:
  name: vietnam-logistics
  labels:
    app: vietnam-logistics

  annotations:
    image.openshift.io/triggers: >-
      [{"from":{"kind":"ImageStreamTag","name":"vietnam-logistics:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"vietnam-logistics\")].image"}]

spec:
  replicas: 1

  selector:
    matchLabels:
      deployment: vietnam-logistics

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%

  template:
    metadata:
      labels:
        deployment: vietnam-logistics

    spec:
      containers:
        - name: vietnam-logistics

          image: vietnam-logistics:latest
          imagePullPolicy: IfNotPresent

          ports:
            - name: http
              containerPort: 8080

          env:
            - name: SPRING_PROFILES_ACTIVE
              value: openshift

          envFrom:
            - configMapRef:
                name: vietnam-logistics-config

            - secretRef:
                name: vietnam-logistics-secret
